apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials 
  namespace: backup 
type: Opaque
stringData:
 config.env: |
  export MINIO_ROOT_USER="minioadmin"
  export MINIO_ROOT_PASSWORD="minioadmin123"
  export MINIO_KMS_AUTO_ENCRYPTION=on
  export MINIO_KMS_SECRET_KEY=minio-key:uKEjj2HFniWShlUbVK/janBaRJp9EycISjw2W641ncw=
