apiVersion: v1
kind: Secret
metadata:
  name: tenant-creds
  namespace: backup 
type: Opaque
stringData:
  config.env: |
    export MINIO_ROOT_USER="minioadmin"
    export MINIO_ROOT_PASSWORD="minioadmin123"
