apiVersion: velero.io/v1
kind: Schedule 
metadata:
  name: minio-integration-backup
  namespace: velero
spec:
  # run backup every 10 minutes every day
  schedule: "*/10 * * * *"
  includedNamespaces:
  - default 
  storageLocation: default
  snapshotVolumes: true
  # delete old backups
  ttl: 00h10m0s
